import type { Metadata } from 'next'

import NavBar from '@/components/NavBar'
import BottomNavbar from '@/components/BottomNavbar'

// These styles apply to every route in the application
import './globals.css'

// Import Analytics and Speed Insights if needed By Vercel
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <NavBar />
                {children}
                <BottomNavbar />
            </body>
        </html>
    )
}
