// src/app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google'; // นำเข้า Inter font
import NavBar from '@/components/NavBar';
import BottomNavbar from '@/components/BottomNavbar'; // BottomNavbar ของคุณ

// These styles apply to every route in the application
import './globals.css';

// กำหนด font
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                {/* เพิ่ม Font Awesome CDN ที่นี่ */}
                {/* ตรวจสอบลิงก์ล่าสุดจาก Font Awesome หรือใช้ React Icons แทน */}
                <link
                    rel="stylesheet"
                    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
                    integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
                    crossOrigin="anonymous"
                    referrerPolicy="no-referrer"
                />
            </head>
            {/* เพิ่มคลาส font และ padding-bottom ให้ body */}
            <body className={`${inter.className} pb-20`}> {/* pb-20 เพื่อเผื่อพื้นที่ให้ BottomNavbar ประมาณ 80px (h-16 + mb-4 = 64px + 16px) */}
                <NavBar />
                {children}
                <BottomNavbar />
            </body>
        </html>
    );
}
